#!/bin/bash

echo "仮想環境が有効化されていることを確認してください。"
echo "以下のコマンドを順番に実行してください："
echo ""
echo "1. 仮想環境の作成（まだの場合）:"
echo "   python3 -m venv venv"
echo ""
echo "2. 仮想環境の有効化:"
echo "   source venv/bin/activate"
echo ""
echo "3. 依存関係のインストール:"
echo "   pip install -r requirements.txt"
echo ""
echo "4. マイグレーションの作成:"
echo "   python manage.py makemigrations"
echo ""
echo "5. マイグレーションの適用:"
echo "   python manage.py migrate"
echo ""
echo "6. 管理者ユーザーの作成（オプション）:"
echo "   python manage.py createsuperuser"